### ISSUE TITLE
 Error when building: `TypeError: Run() takes 2 positional arguments but 3 were given` - MacOS

### ISSUE THREAD

**Issue by maikkundev** [ialex32x/GodotJS#5] opened 2024-08-14 11:30 UTC
OS: MacOS 14.6.1 Sonoma
Godot Branch: 4.2
GodotJS branch: main
SCons version: v4.8.0.7c688f694c644b61342670ce92977bf4a396c0d4
Python 3.11.9

I get the following error when trying to run `scons platform=macos arch=arm64`

```bash
scons: Reading SConscript files ...
Auto-detected 8 CPU cores available for build parallelism. Using 7 cores by default. You can override it with the -j argument.
Building for macOS 11.0+.
MoltenVK found at: /Users/mknndev/VulkanSDK/1.3.290.0/macOS/lib/MoltenVK.xcframework
Building for platform "macos", architecture "arm64", target "editor".
compiling: GodotJS
javascript engine: v8
generate weaver-editor/jsb_project_preset.cpp: no diff
TypeError: Run() takes 2 positional arguments but 3 were given:
  File "/Users/mknndev/Developer/godot/SConstruct", line 1051:
    SConscript("modules/SCsub")
  File "/Users/mknndev/.pyenv/versions/3.11.9/lib/python3.11/site-packages/SCons/Script/SConscript.py", line 684:
    return method(*args, **kw)
  File "/Users/mknndev/.pyenv/versions/3.11.9/lib/python3.11/site-packages/SCons/Script/SConscript.py", line 620:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/Users/mknndev/.pyenv/versions/3.11.9/lib/python3.11/site-packages/SCons/Script/SConscript.py", line 280:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "/Users/mknndev/Developer/godot/modules/SCsub", line 73:
    SConscript(base_path + "/SCsub")
  File "/Users/mknndev/.pyenv/versions/3.11.9/lib/python3.11/site-packages/SCons/Script/SConscript.py", line 684:
    return method(*args, **kw)
  File "/Users/mknndev/.pyenv/versions/3.11.9/lib/python3.11/site-packages/SCons/Script/SConscript.py", line 620:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/Users/mknndev/.pyenv/versions/3.11.9/lib/python3.11/site-packages/SCons/Script/SConscript.py", line 280:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "/Users/mknndev/Developer/godot/modules/GodotJS/SCsub", line 227:
    SConscript("weaver-editor/templates/SCsub")
  File "/Users/mknndev/.pyenv/versions/3.11.9/lib/python3.11/site-packages/SCons/Script/SConscript.py", line 684:
    return method(*args, **kw)
  File "/Users/mknndev/.pyenv/versions/3.11.9/lib/python3.11/site-packages/SCons/Script/SConscript.py", line 620:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/Users/mknndev/.pyenv/versions/3.11.9/lib/python3.11/site-packages/SCons/Script/SConscript.py", line 280:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "/Users/mknndev/Developer/godot/modules/GodotJS/weaver-editor/templates/SCsub", line 8:
    action = env.Run(build_template_ts.make_templates, "Generating GodotJSScript templates header."),
```

**Comment by ialex32x** [comment] 2024-08-15 02:59
Which exact commit (`SHA`) of the 4.2 branch you are on?

**Comment by maikkundev** [comment] 2024-08-15 07:14
```
commit 3504c98c1233bbd2506e89ce46509bc79afaec17 (HEAD -> 4.2, origin/4.2)
Author: Rémi Verschelde <rverschelde@gmail.com>
Date:   Wed Jul 31 22:46:56 2024 +0200

    Revert "[MP] Handle cleanup of "scene cache" nodes"
```

I will try re-cloning the godot repo as I could have messed something up (again lol).

**Comment by ialex32x** [comment] 2024-08-15 08:20
I've tested on macos with the commit `3504c98` of godot, and got no such error. If we identify the commit where the change was introduced, we can then call it with different parameters for various versions accordingly. 

It's the same error in #2.

**Comment by maikkundev** [comment] 2024-08-15 09:01
Ok so I re-tested it and now I'm getting this compilation error...
Sorry if I'm being useless but I have no idea how SCons works and its quirks :/ 

```bash
scons: Reading SConscript files ...
Auto-detected 8 CPU cores available for build parallelism. Using 7 cores by default. You can override it with the -j argument.
Building for macOS 11.0+.
MoltenVK found at: /Users/mknndev/VulkanSDK/1.3.290.0/macOS/lib/MoltenVK.xcframework/macos-arm64_x86_64/
Building for platform "macos", architecture "arm64", target "editor".
compiling: GodotJS
javascript engine: v8
generate weaver-editor/jsb_project_preset.cpp: no diff
generate jsb.gen.h: no diff
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
[Initial build] Compiling modules/GodotJS/weaver-editor/jsb_statistics_viewer.cpp ...
[Initial build] Compiling modules/astcenc/image_compress_astcenc.cpp ...
[Initial build] Compiling thirdparty/basis_universal/encoder/basisu_enc.cpp ...
[Initial build] Compiling thirdparty/basis_universal/encoder/basisu_etc.cpp ...
[Initial build] Compiling thirdparty/basis_universal/encoder/basisu_frontend.cpp ...
[Initial build] Compiling thirdparty/basis_universal/encoder/basisu_gpu_texture.cpp ...
[Initial build] Compiling thirdparty/basis_universal/encoder/basisu_kernels_sse.cpp ...
[Initial build] Linking Static Library modules/libmodule_astcenc.macos.editor.arm64.a ...
[Initial build] Compiling thirdparty/basis_universal/encoder/basisu_pvrtc1_4.cpp ...
Ranlib Library modules/libmodule_astcenc.macos.editor.arm64.a ...
[Initial build] Compiling thirdparty/basis_universal/encoder/basisu_resampler.cpp ...
[Initial build] Compiling thirdparty/basis_universal/encoder/basisu_resample_filters.cpp ...
[Initial build] Compiling thirdparty/basis_universal/encoder/basisu_ssim.cpp ...
[Initial build] Compiling thirdparty/basis_universal/encoder/basisu_uastc_enc.cpp ...
[Initial build] Compiling thirdparty/basis_universal/encoder/pvpngreader.cpp ...
[Initial build] Compiling thirdparty/basis_universal/transcoder/basisu_transcoder.cpp ...
In file included from modules/GodotJS/weaver-editor/jsb_statistics_viewer.cpp:1:
In file included from modules/GodotJS/weaver-editor/jsb_statistics_viewer.h:3:
In file included from ./scene/gui/box_container.h:34:
In file included from ./scene/gui/container.h:34:
In file included from ./scene/gui/control.h:35:
In file included from ./core/object/gdvirtual.gen.inc:5:
In file included from ./core/object/script_instance.h:34:
In file included from ./core/object/ref_counted.h:34:
In file included from ./core/object/class_db.h:34:
In file included from ./core/object/method_bind.h:34:
In file included from ./core/variant/binder_common.h:35:
In file included from ./core/object/object.h:35:
In file included from ./core/object/message_queue.h:38:
./core/variant/variant.h:825:42: error: conversion from 'const unsigned long' to 'Variant' is ambiguous
        Variant args[sizeof...(p_args) + 1] = { p_args..., Variant() }; // +1 makes sure zero sized arrays are also supported.
                                                ^~~~~~
modules/GodotJS/weaver-editor/jsb_statistics_viewer.cpp:80:30: note: in instantiation of function template specialization 'vformat<unsigned long, unsigned long, int>' requested here
    add_row(p_index, p_name, vformat("%d / %d (%d %%)", p_usage, p_total, (int) (((double) p_usage / (double) p_total) * 100)));
                             ^
./core/variant/variant.h:432:2: note: candidate constructor
        Variant(bool p_bool);
        ^
./core/variant/variant.h:433:2: note: candidate constructor
        Variant(signed int p_int); // real one
        ^
./core/variant/variant.h:434:2: note: candidate constructor
        Variant(unsigned int p_int);
        ^
./core/variant/variant.h:439:2: note: candidate constructor
        Variant(signed short p_short); // real one
        ^
./core/variant/variant.h:440:2: note: candidate constructor
        Variant(unsigned short p_short);
        ^
./core/variant/variant.h:441:2: note: candidate constructor
        Variant(signed char p_char); // real one
        ^
./core/variant/variant.h:442:2: note: candidate constructor
        Variant(unsigned char p_char);
        ^
./core/variant/variant.h:443:2: note: candidate constructor
        Variant(int64_t p_int); // real one
        ^
./core/variant/variant.h:444:2: note: candidate constructor
        Variant(uint64_t p_int);
        ^
./core/variant/variant.h:445:2: note: candidate constructor
        Variant(float p_float);
        ^
./core/variant/variant.h:446:2: note: candidate constructor
        Variant(double p_double);
        ^
./core/variant/variant.h:825:42: error: conversion from 'const unsigned long' to 'Variant' is ambiguous
        Variant args[sizeof...(p_args) + 1] = { p_args..., Variant() }; // +1 makes sure zero sized arrays are also supported.
                                                ^~~~~~
./core/variant/variant.h:432:2: note: candidate constructor
        Variant(bool p_bool);
        ^
./core/variant/variant.h:433:2: note: candidate constructor
        Variant(signed int p_int); // real one
        ^
./core/variant/variant.h:434:2: note: candidate constructor
        Variant(unsigned int p_int);
        ^
./core/variant/variant.h:439:2: note: candidate constructor
        Variant(signed short p_short); // real one
        ^
./core/variant/variant.h:440:2: note: candidate constructor
        Variant(unsigned short p_short);
        ^
./core/variant/variant.h:441:2: note: candidate constructor
        Variant(signed char p_char); // real one
        ^
./core/variant/variant.h:442:2: note: candidate constructor
        Variant(unsigned char p_char);
        ^
./core/variant/variant.h:443:2: note: candidate constructor
        Variant(int64_t p_int); // real one
        ^
./core/variant/variant.h:444:2: note: candidate constructor
        Variant(uint64_t p_int);
        ^
./core/variant/variant.h:445:2: note: candidate constructor
        Variant(float p_float);
        ^
./core/variant/variant.h:446:2: note: candidate constructor
        Variant(double p_double);
        ^
2 errors generated.
scons: *** [modules/GodotJS/weaver-editor/jsb_statistics_viewer.macos.editor.arm64.o] Error 1
scons: building terminated because of errors.
[Time elapsed: 00:00:04.130]
```

**Comment by ialex32x** [comment] 2024-08-15 10:45
Oh, my bad, it's a real compiler error (I only tested on Windows at most times). Updating to the latest commit will resolve it.
So far, the main branch is not always stable, I'll create a dev branch after a stable v1.0 :P

**Comment by maikkundev** [comment] 2024-08-15 15:57
It compiles just fine now! :D

**Comment by ialex32x** [comment] 2024-08-16 03:52
Found the cause of this issue, the definition of `env.Run()` defined in `methods.py`  of godot 4.3 is incompatible with 4.2. 
A fix has been commited for this compatibility issue on the main branch.

**Closed by ialex32x** 2024-08-16 03:52 UTC
Labels: bug
